Background setter
fac24/alis-learning pull request #58
Opened 2022-07-21 15:23 UTC by mariaalouisaa

- Save background, text size and font size to local storage
- Display learners colour choice  as background on learner pages
- Import icons on landing page - can animate later
- Make start button dynamic - link to child onboarding if first visit or landing page if not
- Some tweeks to CSS

2022-07-21 15:36 UTC, vasystus approved these changes

2022-07-25 09:28 UTC, joe-dev-public requested changes

2022-07-25 09:28 UTC, joe-dev-public commented on pages/_app.js
> +    "#fff"
Can we change the default background colour to ``#F8F5F4`` instead? It's just off-white so a little less harsh on the eyes. (I got that colour from the [BDA website](https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide) :)

2022-07-25 09:28 UTC, joe-dev-public commented on pages/learner-onboarding/avatar-selection.js
> +  }, []);
Rather than put this in every ``learner-onboarding/`` page, couldn't it just go in the ``LearnerOnboardingLayout.js`` component?

2022-07-25 09:28 UTC, joe-dev-public commented on pages/learner-onboarding/font-selection.js
> +  }, []);
Ditto above.

2022-07-25 09:28 UTC, joe-dev-public commented on pages/learner-onboarding/font-size-selection.js
> +  }, []);
Ditto above.

2022-07-25 09:28 UTC, joe-dev-public commented on pages/learner-onboarding/name.js
> +  }, []);
Ditto above.

2022-07-25 09:28 UTC, joe-dev-public commented on pages/learner-onboarding/onboarding-done.js
> +  }, []);
The ``setOnboarding`` thing can remain in a ``useEffect`` here, but ditto above re the background colour thing.

2022-07-25 09:29 UTC, PJSalter approved these changes

2022-07-25 09:29 UTC, PJSalter commented on pages/index.js
> +        {Object.entries(avatars).map(([avatar_name, avatar_file], index) => (
amazing ✨

2022-07-25 09:29 UTC, PJSalter commented on pages/index.js
> +const ParentStart = styled.a`
wonderful styling, great work ✨

2022-07-25 09:29 UTC, PJSalter commented on pages/learner-onboarding/onboarding-done.js
> +export default function OnboardingDone({
very clear functionality, wonderful work ⭐

2022-07-25 09:49 UTC, joe-dev-public approved these changes

2022-07-25 09:50 UTC, merged